# Generated by Django 5.0.1 on 2024-07-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdb',
            name='phonenumber',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
