# Generated by Django 5.0.1 on 2024-07-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0005_alter_bookingdb_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdb',
            name='phonenumber',
        ),
    ]
