# Generated by Django 5.0.1 on 2024-07-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0006_remove_bookingdb_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdb',
            name='phonenumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
