# Generated by Django 5.0.1 on 2024-07-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0007_bookingdb_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdb',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
